# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Compute the Euclidean distance
#'
#' @param x first vector
#' @param y second vector
#' @export
euclidean <- function(x, y) {
    .Call(`_petal2_euclidean`, x, y)
}

