# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Compute the Euclidean distance
#'
#' @param x first vector
#' @param y second vector
euclidean <- function(x, y) {
    .Call(`_petal2_euclidean`, x, y)
}

#' Compute the metric matrix of a symmetric metric
#' @param X A matrix with the conditions in the rows and the -omics data in the columns
#' @param func a metric function that takes in two vectors of equal length
mmsym <- function(X, func) {
    .Call(`_petal2_mmsym`, X, func)
}

